// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhplbuaduhibsbhiqpuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJocGxidWFkdWhpYnNiaGlxcHVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzODIyMzMsImV4cCI6MjA3OTk1ODIzM30.ZO-154C7IqSGb-WgMEZwCkdBqvb2AAOsQU6t7Rvwx90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});